-- ==============================================================================
-- DO NOT EDIT THIS FILE MANUALLY
-- Static Noise — Generated Palette Table for Neovim
-- Compiled automatically from static-noise (https://github.com/hcastillaq/static-noise)
-- ==============================================================================

local palette = {
  void = "#0F1117",
  base = "#141720",
  raised = "#1A1E2B",
  overlay = "#222738",
  selection = "#242B3D",
  border = "#272C3E",
  borderFocus = "#3D4460",

  text = "#E6E2D6",
  textSoft = "#C9C8C2",
  muted = "#9299AE",
  disabled = "#62697B",

  cyan = "#72EAD5",
  blue = "#83BFFF",
  purple = "#C2A7FF",
  pink = "#F08BC2",
  green = "#A3D98B",
  yellow = "#EDD071",
  orange = "#F3A261",
  red = "#EF7785",

  cyanDim = "#193C3B",
  blueDim = "#20344D",
  purpleDim = "#332B4D",
  pinkDim = "#48283D",
  greenDim = "#293B2C",
  yellowDim = "#443B25",
  orangeDim = "#493124",
  redDim = "#48262E",

  ansi = {
    black = "#141720",
    red = "#EF7785",
    green = "#A3D98B",
    yellow = "#EDD071",
    blue = "#83BFFF",
    magenta = "#C2A7FF",
    cyan = "#72EAD5",
    white = "#E6E2D6",
    bright_black = "#62697B",
    bright_red = "#EF7785",
    bright_green = "#A3D98B",
    bright_yellow = "#EDD071",
    bright_blue = "#83BFFF",
    bright_magenta = "#F08BC2",
    bright_cyan = "#72EAD5",
    bright_white = "#FFFFFF",
  }
}

return palette
