FROM fedora:latest


COPY . /workspace
WORKDIR /workspace

RUN dnf copr enable -y dejan/lazygit
RUN dnf install -y git lazygit fd-find curl ripgrep tree-sitter-cli neovim gcc
RUN dnf clean all

# install lazyvim
RUN git clone https://github.com/LazyVim/starter /root/.config/nvim


# copy static noise
COPY docker/lazyvim/lua/plugins/colorscheme.lua /root/.config/nvim/lua/plugins/colorscheme.lua

CMD [ "sh" ]

