return function(c, config)
  return {
    Normal = { fg = c.content.primary, bg = c.surface.root },
    NormalNC = { fg = c.content.secondary, bg = c.surface.root },
    NormalFloat = { fg = c.content.primary, bg = c.surface.popup },
    FloatBorder = { fg = c.outline.strong, bg = c.surface.popup },
    FloatTitle = { fg = c.interaction.focus, bg = c.surface.popup, bold = true },
    EndOfBuffer = { fg = c.surface.canvas },
    Cursor = { fg = c.interaction.on_focus, bg = c.interaction.focus },
    CursorLine = { bg = c.surface.selection },
    CursorColumn = { bg = c.surface.selection },
    CursorLineNr = { fg = c.interaction.focus, bold = true },
    LineNr = { fg = c.content.subtle },
    SignColumn = { fg = c.content.muted, bg = c.surface.transparent },
    FoldColumn = { fg = c.content.subtle },
    ColorColumn = { bg = c.surface.selection },
    VertSplit = { fg = c.outline.subtle, bg = c.surface.transparent },
    WinSeparator = { fg = c.outline.strong, bg = c.surface.transparent },
    Visual = { fg = c.content.primary, bg = c.surface.selection },
    VisualNOS = { fg = c.content.primary, bg = c.surface.selection },
    Search = { fg = c.status.warning, bg = c.surface.selection },
    IncSearch = { fg = c.interaction.on_focus, bg = c.interaction.focus, bold = true },
    CurSearch = { fg = c.interaction.on_focus, bg = c.interaction.focus, bold = true },
    Substitute = { fg = c.interaction.on_focus, bg = c.status.warning, bold = true },
    MatchParen = { fg = c.interaction.focus, bg = c.surface.selection, bold = true },
    Pmenu = { fg = c.content.secondary, bg = c.surface.popup },
    PmenuSel = { fg = c.content.primary, bg = c.surface.selection, bold = true },
    PmenuSbar = { bg = c.outline.subtle },
    PmenuThumb = { bg = c.outline.strong },
    StatusLine = { fg = c.content.secondary, bg = c.surface.statusline },
    StatusLineNC = { fg = c.content.subtle, bg = c.surface.statusline },
    TabLine = { fg = c.content.muted, bg = c.surface.statusline },
    TabLineFill = { bg = c.surface.canvas },
    TabLineSel = { fg = c.interaction.on_focus, bg = c.interaction.focus, bold = true },
    WinBar = { fg = c.content.secondary, bold = true },
    WinBarNC = { fg = c.content.muted },
    Directory = { fg = c.syntax.function_, bold = true },
    Title = { fg = c.syntax.keyword, bold = true },
    Question = { fg = c.status.success },
    MoreMsg = { fg = c.interaction.focus },
    WarningMsg = { fg = c.status.warning },
    ErrorMsg = { fg = c.status.danger, bold = true },
    ModeMsg = { fg = c.interaction.focus, bold = true },
    QuickFixLine = { fg = c.content.primary, bg = c.surface.selection },
    MsgArea = { fg = c.content.secondary },
    DiagnosticError = { fg = c.status.danger },
    DiagnosticWarn = { fg = c.status.warning },
    DiagnosticInfo = { fg = c.syntax.function_ },
    DiagnosticHint = { fg = c.interaction.focus },
    DiagnosticOk = { fg = c.status.success },
    Folded = { fg = c.content.muted, bg = c.surface.popup },
    NonText = { fg = c.content.subtle },
    SpecialKey = { fg = c.syntax.keyword },
    Whitespace = { fg = c.outline.strong },
    Conceal = { fg = c.content.muted },
  }
end
