return function(c)
  return {
    GitSignsAdd = { fg = c.diff.added_emphasis },
    GitSignsChange = { fg = c.status.warning },
    GitSignsDelete = { fg = c.diff.removed_emphasis },
    NeoTreeNormal = { fg = c.content.primary, bg = c.surface.sidebar },
    NeoTreeNormalNC = { fg = c.content.secondary, bg = c.surface.sidebar },
    NeoTreeRootName = { fg = c.interaction.focus, bold = true },
    NeoTreeDirectoryIcon = { fg = c.interaction.focus },
    NeoTreeDirectoryName = { fg = c.content.primary },
    NeoTreeFileName = { fg = c.content.primary },
    NeoTreeGitAdded = { fg = c.status.success },
    NeoTreeGitModified = { fg = c.syntax.function_ },
    NeoTreeGitDeleted = { fg = c.status.danger },
    NeoTreeGitUntracked = { fg = c.status.warning },
    TelescopeBorder = { fg = c.outline.strong, bg = c.surface.popup },
    TelescopePromptBorder = { fg = c.interaction.focus, bg = c.surface.popup },
    TelescopeNormal = { fg = c.content.primary, bg = c.surface.popup },
    TelescopeSelection = { fg = c.interaction.focus, bg = c.surface.selection, bold = true },
    TelescopeMatching = { fg = c.status.warning, bold = true },
    WhichKey = { fg = c.interaction.focus, bold = true },
    WhichKeyGroup = { fg = c.syntax.function_ },
    WhichKeyDesc = { fg = c.content.primary },
    WhichKeySeparator = { fg = c.content.muted },
    WhichKeyFloat = { bg = c.surface.popup },
    FlashBackdrop = { fg = c.content.subtle },
    FlashLabel = { fg = c.interaction.on_focus, bg = c.status.danger, bold = true },
    TroubleNormal = { fg = c.content.primary, bg = c.surface.popup },
    TroubleText = { fg = c.content.primary },
    TroubleCount = { fg = c.interaction.focus, bold = true },
    TroubleSource = { fg = c.content.muted },
  }
end
