return function(c)
  return {
    GitSignsAdd = { fg = c.diff.added_emphasis },
    GitSignsChange = { fg = c.status.warning },
    GitSignsDelete = { fg = c.diff.removed_emphasis },
    GitSignsUntracked = { fg = c.status.warning },
    NeoTreeNormal = { fg = c.content.primary, bg = c.surface.sidebar },
    NeoTreeNormalNC = { fg = c.content.secondary, bg = c.surface.sidebar },
    NeoTreeRootName = { fg = c.interaction.focus, bold = true },
    NeoTreeDirectoryIcon = { fg = c.interaction.focus },
    NeoTreeDirectoryName = { fg = c.content.primary },
    NeoTreeFileName = { fg = c.content.primary },
    NeoTreeGitAdded = { fg = c.status.success },
    NeoTreeGitModified = { fg = c.syntax.function_ },
    NeoTreeGitDeleted = { fg = c.status.danger },
    NeoTreeGitUntracked = { fg = c.status.warning },
    SnacksPickerGitStatusAdded = { fg = c.status.success },
    SnacksPickerGitStatusModified = { fg = c.syntax.function_ },
    SnacksPickerGitStatusDeleted = { fg = c.status.danger },
    SnacksPickerGitStatusUntracked = { fg = c.status.warning, bold = true },
    SnacksPickerGitStatusStaged = { fg = c.interaction.focus },
    SnacksPickerGitStatusUnmerged = { fg = c.status.danger, bold = true },
    SnacksPickerGitStatusIgnored = { fg = c.content.subtle },
    SnacksPicker = { fg = c.content.primary, bg = c.surface.sidebar },
    SnacksPickerList = { fg = c.content.primary, bg = c.surface.sidebar },
    SnacksPickerListCursorLine = { fg = c.content.primary, bg = c.surface.selection },
    SnacksPickerInput = { fg = c.content.primary, bg = c.surface.sidebar },
    SnacksPickerInputBorder = { fg = c.outline.subtle, bg = c.surface.sidebar },
    SnacksPickerInputTitle = { fg = c.interaction.focus, bg = c.surface.elevated, bold = true },
    SnacksPickerTitle = { fg = c.interaction.focus, bg = c.surface.elevated, bold = true },
    SnacksPickerBorder = { fg = c.outline.subtle, bg = c.surface.sidebar },
    SnacksPickerDirectory = { fg = c.syntax.function_, bold = true },
    SnacksPickerDir = { fg = c.content.muted },
    SnacksPickerFile = { fg = c.content.primary },
    SnacksPickerTotals = { fg = c.content.muted },
    SnacksPickerMatch = { fg = c.status.warning, bold = true },
    TelescopeBorder = { fg = c.outline.strong, bg = c.surface.popup },
    TelescopePromptBorder = { fg = c.interaction.focus, bg = c.surface.popup },
    TelescopeNormal = { fg = c.content.primary, bg = c.surface.popup },
    TelescopeSelection = { fg = c.interaction.focus, bg = c.surface.selection, bold = true },
    TelescopeMatching = { fg = c.status.warning, bold = true },
    WhichKey = { fg = c.interaction.focus, bold = true },
    WhichKeyGroup = { fg = c.syntax.function_ },
    WhichKeyDesc = { fg = c.content.primary },
    WhichKeySeparator = { fg = c.content.muted },
    WhichKeyFloat = { bg = c.surface.popup },
    FlashBackdrop = { fg = c.content.subtle },
    FlashLabel = { fg = c.interaction.on_focus, bg = c.status.danger, bold = true },
    TroubleNormal = { fg = c.content.primary, bg = c.surface.popup },
    TroubleText = { fg = c.content.primary },
    TroubleCount = { fg = c.interaction.focus, bold = true },
    TroubleSource = { fg = c.content.muted },
  }
end
