local paths = require("scripts.lib.paths")
local log = require("scripts.lib.log")
local M = {}

local LUA_RESERVED_WORDS = {
  ["and"] = true, ["break"] = true, ["do"] = true, ["else"] = true,
  ["elseif"] = true, ["end"] = true, ["false"] = true, ["for"] = true,
  ["function"] = true, ["goto"] = true, ["if"] = true, ["in"] = true,
  ["local"] = true, ["nil"] = true, ["not"] = true, ["or"] = true,
  ["repeat"] = true, ["return"] = true, ["then"] = true, ["true"] = true,
  ["until"] = true, ["while"] = true,
}

local function write_file(path, lines)
  if vim.fn.writefile(lines, path) ~= 0 then
    error("static-noise build: cannot write " .. path, 0)
  end
end

local function fail(message)
  log.error(message)
  error("static-noise build: " .. message, 0)
end

local function read_snapshot(path)
  local ok, lines = pcall(vim.fn.readfile, path)
  if not ok then
    fail("cannot read " .. path .. ": " .. tostring(lines))
  end
  local ok_decode, snapshot = pcall(vim.json.decode, table.concat(lines, "\n"))
  if not ok_decode then
    fail("invalid JSON in " .. path .. ": " .. tostring(snapshot))
  end
  return snapshot
end

local function is_color(value)
  return type(value) == "string" and value:match("^#%x%x%x%x%x%x$") ~= nil
end

local function resolve_snapshot(snapshot)
  local function lookup(path)
    local value = snapshot
    for segment in path:gmatch("[^.]+") do
      if type(value) ~= "table" then
        return nil
      end
      value = value[segment]
    end
    return value
  end

  local resolving = {}
  local function resolve(path)
    if resolving[path] then
      fail("circular token reference at " .. path)
    end
    resolving[path] = true
    local token = lookup(path)
    if type(token) ~= "table" or token["$value"] == nil then
      fail("missing token reference " .. path)
    end
    local value = token["$value"]
    if type(value) == "string" and value:match("^{[^}]+}$") then
      value = resolve(value:sub(2, -2))
    end
    resolving[path] = nil
    if not is_color(value) then
      fail("token " .. path .. " is not a six-digit hex color")
    end
    return value:upper()
  end

  local function convert(node, path)
    if type(node) ~= "table" then
      fail("expected object at " .. path)
    end
    if node["$value"] ~= nil then
      return resolve(path)
    end
    local result = {}
    for key in pairs(node) do
      if key:sub(1, 1) ~= "$" then
        result[key] = convert(node[key], path .. "." .. key)
      end
    end
    return result
  end

  local resolved = {}
  for _, section in ipairs({ "primitives", "semantic", "domains", "projections" }) do
    if type(snapshot[section]) ~= "table" then
      fail("missing top-level section " .. section)
    end
    resolved[section] = convert(snapshot[section], section)
  end
  return resolved
end

local function serialize(value, indent)
  if type(value) == "string" then
    return string.format("%q", value)
  end
  indent = indent or 0
  local padding = string.rep(" ", indent + 2)
  local closing = string.rep(" ", indent)
  local keys = {}
  for key in pairs(value) do
    keys[#keys + 1] = key
  end
  table.sort(keys)

  local lines = { "{" }
  for _, key in ipairs(keys) do
    local identifier = key:match("^[%a_][%w_]*$")
    local field = identifier and not LUA_RESERVED_WORDS[key] and key or "[" .. string.format("%q", key) .. "]"
    lines[#lines + 1] = padding .. field .. " = " .. serialize(value[key], indent + 2) .. ","
  end
  lines[#lines + 1] = closing .. "}"
  return table.concat(lines, "\n")
end

-- Build accepts explicit input/output paths so sync can validate a staged candidate.
function M.run(root, input, output, quiet)
  input = input or paths.snapshot(root)
  output = output or paths.generated_palette(root)
  log.info("reading palette snapshot: " .. input)
  local resolved = resolve_snapshot(read_snapshot(input))
  log.info("resolved canonical tokens")
  local generated = "-- DO NOT EDIT: generated by scripts/main.lua from upstream/palette.json.\n\nreturn " .. serialize(resolved) .. "\n"
  local temporary = output .. ".tmp-" .. tostring(vim.fn.getpid())
  write_file(temporary, vim.split(generated, "\n", { plain = true, trimempty = true }))
  log.info("writing generated palette")
  if vim.fn.rename(temporary, output) ~= 0 then
    vim.fn.delete(temporary)
    fail("cannot replace " .. output)
  end
  if not quiet then
    log.success("generated palette: " .. output)
  end
end

return M
